import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MrAks Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` bg-[#d5d5df] relative max-w-[1400px]  mx-auto  `} >
        <div className="grid grid-cols-3 items-center px-30 pt-30 absolute w-[100%] ">
          <div className="yellow"></div>
          <div className="red"></div>
          <div className="blue"></div>
        </div>
        <div className="grid grid-cols-3 items-center px-30 pt-30 absolute w-[100%] top-220 left-0 ">
          <div className="yellow"></div>
          <div className="red"></div>
          <div className="blue"></div>
        </div>
        <div className="w-full  p-23 pt-15 bg-[#ffffff67] backdrop-blur-xl absolute top-0 left-0 ">
          <Navbar />

          {children}
        </div>
     

      </body>
    </html>
  );
}
